version: "3.7"

services:
  mini-project-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/mini-project/

    ports:
      - 3000:3000

  mini-project-database:
    image: mongo:5
    ports:
      - 27017:27017
