paths:
    /starbucks:
        get:
            summary: 스타벅스 커피목록 조회
            tags: [Starbucks]
            responses:
                "200":
                    description: 성공
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    properties:
                                        _id:
                                            type: string
                                            example: "63207182d04e2ad39aa00aa5"
                                        name:
                                            type: string
                                            example: 블랙 글레이즈드 라떼
                                        img:
                                            type: string
                                            example: "https://image.istarbucks.co.kr/upload/store/skuimg/2022/08/[9200000002…"
