paths:
    /user:
        post:
            summary: 유저 추가하기
            tags: [Users]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    example: 철수
                                email:
                                    type: string
                                    example: aaa123@naver.com
                                prefer:
                                    type: string
                                    example: https://www.naver.com/
                                pwd:
                                    type: string
                                    example: "1234"
                                phone:
                                    type: string
                                    example: "01022223344"
                                personal:
                                    type: string
                                    example: 123411-1122222
            responses:
                "200":
                    description: 성공
                    content:
                        application/json:
                            schema:
                                type: string
                                example: 61ee1b7272a81036fc429a05
                "422":
                    description: 실패
                    content:
                        application/json:
                            schema:
                                type: string
                                example: 에러! 핸드폰 번호가 인증되지 않았습니다.
    /users:
        get:
            summary: 유저 목록조회
            tags: [Users]
            responses:
                "200":
                    description: 성공
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    properties:
                                        name:
                                            type: string
                                            example: 철수
                                        email:
                                            type: string
                                            example: example@example.com
                                        prefer:
                                            type: string
                                            example: http://www.naver.com
                                        pwd:
                                            type: string
                                            example: "1234"
                                        phone:
                                            type: string
                                            example: "01012345678"
                                        personal:
                                            type: string
                                            example: 111111-1111111
                                        og:
                                            type: object
                                            properties:
                                                title:
                                                    type: string
                                                    example: 네이버
                                                description:
                                                    type: string
                                                    example: 네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요
                                                image:
                                                    type: string
                                                    example: https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png
