version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
      # - ./*.js:/myfolder/email.js

    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  my-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydev09'
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - 3306:3306
