# 설정파일 yml /yaml (야믈파일)
# json은 객체형태로{}그룹핑, 야믈파일은 들여쓰기로 그룹핑함.

version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  my-databaes:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
# services :컴퓨터 / my-backend 와 my-databaes 만듬
# context: .  현재위치에 도커파일잇어요
# dockerfile: Dockerfile 도커파일이름이 뭔데: 도커파일이에요
# 포트포어딩도 미리 지정할수있음 ports: - 3000:3000
# version, services, volumes, networks 중
